security:
    providers:
        chain_provider:
            chain:
                providers: [webservice, http]
        webservice:
            id: sioweb.api.security.webservice.provider
        http:
            id: sioweb.api.security.http.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: "^/api"
            anonymous: true
            logout: true
            guard:
                authenticators:
                    - sioweb.api.security.webservice.authenticator
                    - sioweb.api.security.http.authenticator
                entry_point: sioweb.api.security.webservice.authenticator
