security:
    providers:
        webservice:
            id: sioweb.api.security.user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: '^/api'
            anonymous: true
            logout: true
            guard:
                authenticators: 
                    # - "@sioweb.api.security.tokenauthenticator"
                    # - Sioweb\Oxid\Api\Security\TokenAuthenticator
                    - sioweb.api.security.tokenauthenticator